export const PEOPLE = [
  {
    id: 0,
    name: 'Elizabeth Bathory',
    image: require('../assets/images/ElizabethBathory.png'),
    born: 1560,
    died: 1640,
    featured: true,
    previewText:
      'Hungarian countess Elizabeth Bathory is thought to have murdered hundreds of young women in the early 17th century.',
    description:
      'Bathory was born on August 7, 1560, in Nyírbátor, Hungary. She was born to prominent Protestant nobility. Her family controlled Transylvania and her uncle, Stephen Bathory, was the king of Poland. She was raised in the family castle in Ecséd, Hungary. In 1575, at the age of 15, she married Count Ferencz Nádasdy, another noble person. He was a Hungarian national hero fighting against the Turks. They moved to Castle Cachtrice, a wedding gift from her husband’s family, and had four children. There had been rumors regarding the deaths of maids in Bathory’s household but she quickly had the bodies buried, blaming cholera as the cause of death and contagion being the reasoning for quick burial. However, once her husband died in 1604, the deaths in her household greatly increased. It is believed that she used the violence as a coping mechanism and after her husband’s death, she needed her particular form of stress relief even more. Since no exactly written records exist of Bathory’s thoughts, we are not able to definitely know her reason for torture or even her cohorts. It’s believed that she learned cruelty, maybe even torture, from her aunt, with whom she lived during her youth. Some speculate that her husband knew and even participated, building her a torture room in their castle. It is known that one of her senior maids engaged in the torture. In the sixteenth and seventeenth centuries, the poor had nearly no way to defend themselves against the wealthy. Rumors had existed for years when so many maids had died while working for her. However, once she ran out of servants to torture, she began kidnapping the daughters of other noble families, who began to notice their female relations were going missing. Matthias, the King of Hungary, ordered the Count Palatine of Hungary, György Thurzó (also Bathory’s cousin) to investigate. After interviewing people in the area, the count palatine estimated that Bathory had murdered more than 600 girls with the assistance of her servants. In December 30, 1609, Bathory and her servants were arrested. The servants were convicted and executed quickly. Bathotry was held captive instead of execution, as was standard for the wealthy at that time. Bathory was bricked into a room of her castle for the rest of her life with only small holes in the brick for the passage of food and waste. She died in captivity.',
  },
  {
    id: 1,
    name: 'Rosa Parks',
    image: require('../assets/images/RosaParks.png'),
    born: 1913,
    died: 2005,
    featured: true,
    previewText: 'An arrest on a bus for civil rights. See Stories for more.',
    description:
      'On December 1, 1955; Rosa Parks was arrested for breaking an Alabama law requiring black passengers to give up their seats to whites when the bus was full. Blacks also had to sit in the back, behind all white passengers. Her arrest sparked a boycott of the bus system in Montgomery, Alabama, that lasted 381 days. The arrest and boycott also led to a 1956 Supreme Court decision banning segregation on public transportation. Rosa Parks was active in her local chapter of the National Association for the Advancement of Colored People (NAACP). The NAACP sought to challenge segregation on public transportation but Parks’ arrest was not planned. Previously, another African American woman had been arrested for refusing to give up her seat on a bus, but the NAACP believed the unmarried teenaged mother wouldn’t look proper as the face of the struggle to end segregation. A one day boycott of African Americans began on Parks’ court date of December 5. Black people constituted 70 percent of the transit system’s customers so the buses ran mostly empty that day. The overwhelming success of the boycott inspired further sustained action. Religious and political leaders met at the Dexter Avenue Baptist Church and formed the Montgomery Improvement Association (later the Southern Christian Leadership Conference, SCLC). Reverend Martin Luther King, Jr. was appointed the leader of the organization. For the next year, they coordinated the bus boycott. A carpool system of approximately 300 cars was created to assist those boycotting get around town. Others walked for miles for more than a year to get to and from work. During the boycott, the homes of King and another leader were bombed. Montgomery officials indicted more than 80 boycott leaders under a 1921 law prohibiting conspiracies that interfered with lawful business. King was tried and convicted on the charge and ordered to pay $500 or serve 386 days in jail. Despite the harassment, the boycott continued. One year later, in 1956: the US Supreme Court banned segregation on public transportation and the boycott in Montogomery ended. Rosa Parks moved to Detroit, Michigan, and worked doe Congressman John Conyers. She earned several national awards and was granted twenty honorary doctorates from universities around the world. Parks passed in 2005 at the age of ninety-two and became the first woman to lie in honor in the US Capitol Rotunda.',
  },
];
